---
services:
  watchtower:
    environment:
      - WATCHTOWER_LABEL_ENABLE=1
      - WATCHTOWER_DEBUG=1
      - NO_COLOR=1
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 3600
    restart: unless-stopped
  sprintf:
    image: ghcr.io/yaleman/sprintf:latest
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      com.centurylinklabs.watchtower.enable: true
    ports:
      - "127.0.0.1:8090:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sprintf-healthcheck"]
      interval: 60s
      timeout: 2s
      retries: 5
