---
version: '3.8'

services:
  watchtower:
    # env_file: .env
    environment:
      - WATCHTOWER_LABEL_ENABLE=1
      - WATCHTOWER_DEBUG=1
      - NO_COLOR=1
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 3600
  sprintf:
    build: .
    healthcheck:
      test: ["CMD", "curl",
        "-f",
        "-s",
        "http://127.0.0.1:8000/up",
        ]
      interval: 60s
      timeout: 1s
      retries: 5
    image: ghcr.io/yaleman/sprintf:latest
    labels:
      com.centurylinklabs.watchtower.enable: true
    ports:
      - "127.0.0.1:8090:8000"
    restart: always
