---
name: "Build container"
"on":
  workflow_dispatch:
  push:
  pull_request:

permissions:
  packages: write
  contents: read
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      output: image
      push: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
      platforms: linux/amd64,linux/arm64
      meta-images: ghcr.io/${{ github.repository }}
      meta-tags: |
        type=ref,event=branch
        type=ref,event=pr
        type=sha
        type=raw,value=latest,enable={{is_default_branch}}
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
